DROP TABLE MOVIMENTACAO;
DROP TABLE PRODUTO;
DROP TABLE FUNCIONARIO;

CREATE TABLE FUNCIONARIO (ID_FUNCIONARIO INTEGER PRIMARY KEY
, NOME VARCHAR(50) NOT NULL
, CPF VARCHAR(14) NOT NULL
, IDADE INTEGER NOT NULL
, CARGO VARCHAR(50) NOT NULL
, SENHA VARCHAR(100)NOT NULL
, SEXO VARCHAR(1) NOT NULL);

CREATE TABLE PRODUTO (ID_PRODUTO INTEGER PRIMARY KEY
, CATEGORIA VARCHAR(50) NOT NULL
, NOME VARCHAR(100) NOT NULL 
, TAMANHO VARCHAR(20) NOT NULL
, PRECO VARCHAR(100) NOT NULL
, QUANTIDADE INTEGER NOT NULL);

CREATE TABLE MOVIMENTACAO (ID_MOVIMENTACAO INTEGER PRIMARY KEY 
, TIPO_MOVIMENTACAO VARCHAR(50) NOT NULL
, ID_FUNCIONARIO INTEGER
, ID_PRODUTO INTEGER NOT NULL
, QUANTIDADE INTEGER NOT NULL
, DATA_MOVIMENTACAO DATETEXT(20) NOT NULL
, FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
, FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO));


INSERT INTO FUNCIONARIO (ID_FUNCIONARIO, NOME, CPF, IDADE, CARGO, SENHA, SEXO) VALUES(1, 'LEANDRO', '378.068.248-63', 25, 'DIRETOR', '8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918','MASCULINO'); 
INSERT INTO FUNCIONARIO (ID_FUNCIONARIO, NOME, CPF, IDADE, CARGO, SENHA, SEXO) VALUES(2, 'MARCUS', '376.129.474-39', 20, 'GERENTE', '8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918','MASCULINO');
INSERT INTO FUNCIONARIO (ID_FUNCIONARIO, NOME, CPF, IDADE, CARGO, SENHA, SEXO) VALUES(3, 'FLAVIA', '249.974.213-59', 18, 'ANALISTA TECNICO', '8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918','FEMININO');                               )

INSERT INTO PRODUTO (ID_PRODUTO, CATEGORIA, NOME, TAMANHO, PRECO, QUANTIDADE) VALUES(1, 'BEBIDAS', 'COCA COLA', '1 LITRO', '2,50', 300);
INSERT INTO PRODUTO (ID_PRODUTO, CATEGORIA, NOME, TAMANHO, PRECO, QUANTIDADE) VALUES(2, 'SALGADOS', 'COXINHA', 'MEDIO', '1,50', 450);
INSERT INTO PRODUTO (ID_PRODUTO, CATEGORIA, NOME, TAMANHO, PRECO, QUANTIDADE) VALUES(3, 'BEBIDAS', 'SUCO DE LARANJA', '2 LITROS', '3,50', 620);

INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, TIPO_MOVIMENTACAO, ID_FUNCIONARIO, ID_PRODUTO, QUANTIDADE, DATA_MOVIMENTACAO) VALUES(1, 'ENTRADA', 1, 1, 21, '05/06/2016');
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, TIPO_MOVIMENTACAO, ID_FUNCIONARIO, ID_PRODUTO, QUANTIDADE, DATA_MOVIMENTACAO) VALUES(2, 'VENDA', 2, 2, 40, '07/06/2016');
INSERT INTO MOVIMENTACAO (ID_MOVIMENTACAO, TIPO_MOVIMENTACAO, ID_FUNCIONARIO, ID_PRODUTO, QUANTIDADE, DATA_MOVIMENTACAO) VALUES(3, 'ENTRADA', 3, 3, 35, '08/06/2016');